language: ruby
rvm:
  - 2.2.4
  - 2.3.0
gemfile:
  - gemfiles/as_3.2.gemfile
  - gemfiles/as_4.0.gemfile
  - gemfiles/as_4.1.gemfile
  - gemfiles/as_4.2.gemfile
before_install: gem install bundler -v 1.11.2
script: bundle exec rake spec
